Fix pairings being loaded before transports
This fixes an issue I observed locally, where running `aiohomekitctl` with any existing IP pairing would throw an error:

```
controller.py:0185 ERROR Skipped pairing: Transport IP not supported. See setup.py for required dependencies.
```

After tracing, I discovered this is because the pairings were loaded before the transports, and moving the load_data call to this new location seemed to have fixed it for me.