Ensure missing dbus is trapped at startup via FileNotFoundError
Fixes
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/__init__.py", line 249, in async_setup
    await async_get_controller(hass)
  File "/usr/src/homeassistant/homeassistant/components/homekit_controller/utils.py", line 45, in async_get_controller
    await controller.async_start()
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/controller.py", line 101, in async_start
    await self._async_register_backend(
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/controller.py", line 81, in _async_register_backend
    self._transports.append(await self._tasks.enter_async_context(controller))
  File "/usr/local/lib/python3.10/contextlib.py", line 619, in enter_async_context
    result = await _cm_type.__aenter__(cm)
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/abstract.py", line 318, in __aenter__
    await self.async_start()
  File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/controller.py", line 63, in async_start
    await self._scanner.start()
  File "/usr/local/lib/python3.10/site-packages/bleak/backends/bluezdbus/scanner.py", line 88, in start
    self._bus = await MessageBus(bus_type=BusType.SYSTEM).connect()
  File "/usr/local/lib/python3.10/site-packages/dbus_next/aio/message_bus.py", line 122, in __init__
    super().__init__(bus_address, bus_type, ProxyObject)
  File "/usr/local/lib/python3.10/site-packages/dbus_next/message_bus.py", line 85, in __init__
    self._setup_socket()
  File "/usr/local/lib/python3.10/site-packages/dbus_next/message_bus.py", line 575, in _setup_socket
    raise err
  File "/usr/local/lib/python3.10/site-packages/dbus_next/message_bus.py", line 548, in _setup_socket
    self._sock.connect(filename)
FileNotFoundError: [Errno 2] No such file or directory
```