Small fixes for BLE devices
- Remove notify workaround since we are now using
  a new BleakClient object every time and the problem
  goes away

- Fix missing minStep/minValue/maxValue resulting in
  unexpected errors when changing color temp (etc)

Fixes
```
2022-07-25 17:01:26.391 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [4449491824] Nanoleaf Light Bulb (C8F2A86D-F301-67C3-48AE-EC9280F5A18C): PDU status was not success: Invalid request (6)
Traceback (most recent call last):
  File "/Users/bdraco/home-assistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/Users/bdraco/home-assistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/Users/bdraco/home-assistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/Users/bdraco/home-assistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/Users/bdraco/home-assistant/homeassistant/helpers/service.py", line 676, in entity_service_call
    future.result()  # pop exception if have
  File "/Users/bdraco/home-assistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/Users/bdraco/home-assistant/homeassistant/helpers/service.py", line 713, in _handle_entity_call
    await result
  File "/Users/bdraco/home-assistant/homeassistant/components/light/__init__.py", line 553, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/Users/bdraco/home-assistant/homeassistant/components/homekit_controller/light.py", line 144, in async_turn_on
    await self.async_put_characteristics(characteristics)
  File "/Users/bdraco/home-assistant/homeassistant/components/homekit_controller/__init__.py", line 109, in async_put_characteristics
    return await self._accessory.put_characteristics(payload)
  File "/Users/bdraco/home-assistant/homeassistant/components/homekit_controller/connection.py", line 633, in put_characteristics
    results = await self.pairing.put_characteristics(characteristics)
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 102, in _async_wrap
    return await func(self, *args, **kwargs)
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 63, in _async_wrap
    return await func(*args, **kwargs)
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 745, in put_characteristics
    await self._async_request(OpCode.CHAR_WRITE, iid, payload)
  File "/Users/bdraco/home-assistant/venv/lib/python3.10/site-packages/aiohomekit/controller/ble/pairing.py", line 282, in _async_request
    raise ValueError(
ValueError: Nanoleaf Light Bulb (C8F2A86D-F301-67C3-48AE-EC9280F5A18C): PDU status was not success: Invalid request (6)```